Build caching

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,6 +13,10 @@ defaults:
   run:
     shell: bash
 
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
+
 jobs:
   pre-commit:
     name: Pre-Commit
@@ -33,46 +37,72 @@ jobs:
       run: pre-commit run --all-files --show-diff-on-failure
 
   build:
-    name: Build / ${{matrix.kind.name}}
+    name: Build / ${{ matrix.kind.name }}
     needs: pre-commit
-    runs-on: ${{matrix.kind.os}}
+    runs-on: ${{ matrix.kind.os }}
 
     strategy:
       fail-fast: false
       matrix:
         kind:
-        - { name: Windows-VS2022-x64-Release, os: windows-2022,  config: Release, flags: -A x64 -DEXTENDED_CHAR_SET=ASCII }
-        - { name: Windows-VS2022-x64-Debug,   os: windows-2022,  config: Debug,   flags: -A x64 -DEXTENDED_CHAR_SET=ASCII }
-        - { name: Windows-VS2022-x86-Release, os: windows-2022,  config: Release, flags: -A Win32 -DEXTENDED_CHAR_SET=ASCII }
-        # - { name: Windows-VS2022-x86-Debug,   os: windows-2022,  config: Debug,   flags: -A Win32 -DEXTENDED_CHAR_SET=ASCII }
-        - { name: Ubuntu-GCC-x64-Release,     os: ubuntu-latest, config: Release, flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DEXTENDED_CHAR_SET=ASCII }
-        # - { name: Ubuntu-GCC-x64-Debug,       os: ubuntu-latest, config: Debug,   flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DEXTENDED_CHAR_SET=ASCII }
-        - { name: Ubuntu-Clang-x64-Release,   os: ubuntu-latest, config: Release, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DEXTENDED_CHAR_SET=ASCII }
-        # - { name: Ubuntu-Clang-x64-Debug,     os: ubuntu-latest, config: Debug,   flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DEXTENDED_CHAR_SET=ASCII }
+        - { name: Windows-VS2022-x64-Release, os: windows-2022,  arch: x64, config: Release, flags: -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" -DEXTENDED_CHAR_SET=ASCII }
+        - { name: Windows-VS2022-x86-Release, os: windows-2022,  arch: x86, config: Release, flags: -DCMAKE_C_COMPILER="cl.exe" -DCMAKE_CXX_COMPILER="cl.exe" -DEXTENDED_CHAR_SET=ASCII }
+        - { name: Ubuntu-GCC-x64-Release,     os: ubuntu-latest, arch: x64, config: Release, flags: -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DEXTENDED_CHAR_SET=ASCII }
+        - { name: Ubuntu-Clang-x64-Release,   os: ubuntu-latest, arch: x64, config: Release, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DEXTENDED_CHAR_SET=ASCII }
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Setup
+      - name: Setup (Windows)
+        if: matrix.kind.os == 'windows-2022'
+        run: |
+          choco install ninja -y
+
+      - name: Setup (Ubuntu)
         if: matrix.kind.os == 'ubuntu-latest'
         run: |
           chmod +x setup_ubuntu.sh
           ./setup_ubuntu.sh
 
-      - name: Configure
-        run: cmake -B build ${{matrix.kind.flags}} -DCMAKE_BUILD_TYPE=${{matrix.kind.config}}
+      - name: Cache dependencies
+        uses: actions/cache@v4
+        with:
+          path: |
+            build/_deps
+          key: deps-${{ matrix.kind.name }}-${{ hashFiles('CMakeLists.txt') }}
+          restore-keys: |
+            deps-${{ matrix.kind.name }}-
+
+      - name: Cache build
+        uses: hendrikmuhs/ccache-action@v1.2
+        with:
+          variant: sccache
+          key: ${{ matrix.kind.name }}-${{ github.event.pull_request.head.ref || github.ref_name }}
+          restore-keys: |
+            ${{ matrix.kind.name }}-${{ github.event.pull_request.base.ref || github.ref_name }}
+          max-size: 500M
+          append-timestamp: false
+
+      - name: Configure environment (Windows)
+        if: matrix.kind.os == 'windows-2022'
+        uses: ilammy/msvc-dev-cmd@v1
+        with:
+          arch: ${{ matrix.kind.arch }}
+
+      - name: Configure build
+        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.kind.config }} -DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache ${{ matrix.kind.flags }}
 
       - name: Build
-        run: cmake --build build --config ${{matrix.kind.config}} --parallel 4
+        run: cmake --build build --config ${{ matrix.kind.config }} --parallel ${{ runner.cores }}
 
-      - name: Show files recursively
-        run: tree -a || (echo "tree not found, listing recursively"; ls -laR)
+      # - name: Show files recursively
+      #   run: tree -a || (echo "tree not found, listing recursively"; ls -laR)
 
       - name: Upload binaries
         uses: actions/upload-artifact@v4
         with:
-          name: Chemgine-${{matrix.kind.name}}
+          name: Chemgine-${{ matrix.kind.name }}
           compression-level: 9
           path: |
             build/gui_app/**/gui_app*
@@ -84,34 +114,27 @@ jobs:
             !**/CMakeFiles/**
 
   unit:
-    name: Unit / ${{matrix.kind.name}}
+    name: Unit / ${{ matrix.kind.name }}
     needs: build
-    runs-on: ${{matrix.kind.os}}
+    runs-on: ${{ matrix.kind.os }}
 
     strategy:
       fail-fast: false
       matrix:
         kind:
         - { name: Windows-VS2022-x64-Release, os: windows-2022,  config: Release }
-        - { name: Windows-VS2022-x64-Debug,   os: windows-2022,  config: Debug }
         - { name: Windows-VS2022-x86-Release, os: windows-2022,  config: Release }
-        # - { name: Windows-VS2022-x86-Debug,   os: windows-2022,  config: Debug }
         - { name: Ubuntu-GCC-x64-Release,     os: ubuntu-latest, config: Release }
-        # - { name: Ubuntu-GCC-x64-Debug,       os: ubuntu-latest, config: Debug }
-        # - { name: Ubuntu-Clang-x64-Release,   os: ubuntu-latest, config: Release }
-        # - { name: Ubuntu-Clang-x64-Debug,     os: ubuntu-latest, config: Debug }
+        - { name: Ubuntu-Clang-x64-Release,   os: ubuntu-latest, config: Release }
 
     steps:
       - uses: actions/download-artifact@v4
         with:
-          name: Chemgine-${{matrix.kind.name}}
-
-      - name: Show files recursively
-        run: tree -a || (echo "tree not found, listing recursively"; ls -laR)
+          name: Chemgine-${{ matrix.kind.name }}
 
       - name: Run unit tests (Windows)
         if: matrix.kind.os == 'windows-2022'
-        working-directory: ./test_app/${{matrix.kind.config}}/
+        working-directory: ./test_app/
         run: ./test_app.exe -u
 
       - name: Run unit tests (Ubuntu)
